### ISSUE TITLE
Docker Image doesn't generate slides

### ISSUE THREAD

**Issue by aazon** [tangramor/slidev_docker#1]
## Steps to reproduce

- Start slidev in Docker as described in the `README.md`
- Navigate to `localhost:3030`

## Expected results

Slides in the browser

## Actual result:

There is an error in the output:

```
Element is missing end tag.
6:57:02 PM [vite] Internal server error: Element is missing end tag.
  Plugin: vite:vue
  File: /@slidev/slides/1.md
  8  |    </span>
  9  |  </div>
  10 |  <p><a href="https://github.com/slidevjs/slidev" target="_blank" alt="GitHub"
     |      ^
  11 |    class="abs-br m-6 text-xl icon-btn opacity-50 !border-none !hover:text-white"></p>
  12 |    <carbon-logo-github />
      at createCompilerError (/slidev/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:19:19)
      at emitError (/slidev/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:1594:29)
      at parseElement (/slidev/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:1146:9)
      at parseChildren (/slidev/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:937:28)
      at parseElement (/slidev/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:1125:22)
      at parseChildren (/slidev/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:937:28)
      at parseElement (/slidev/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:1125:22)
      at parseChildren (/slidev/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:937:28)
      at parseElement (/slidev/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:1125:22)
      at parseChildren (/slidev/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:937:28)
```

**Comment by tangramor** [comment]
It's a bug of slidev but not the docker image. In fact this image just give us a nodejs environment and automatically npm install the slidev packages.

To remove the error, you may check the slidev.md file, modify this (about line 29): 
```
<a href="https://github.com/slidevjs/slidev" target="_blank" alt="GitHub"
  class="abs-br m-6 text-xl icon-btn opacity-50 !border-none !hover:text-white">
  <carbon-logo-github />
</a>
```

to

```
<a href="https://github.com/slidevjs/slidev" target="_blank" alt="GitHub" class="abs-br m-6 text-xl icon-btn opacity-50 !border-none !hover:text-white">
  <carbon-logo-github />
</a>
```

This error is introduced by node_modules/@slidev/cli/template.md . It worked well before...
