### ISSUE TITLE
Export functionality

### ISSUE THREAD

**Issue by fam4r** [tangramor/slidev_docker#6]
Hello,

is there a way - using this docker image - to export the slides (e.g. to PDF format)?

For example by specifying the `export` command to the `docker run` command:

```bash
docker run --name slidev --rm -it \
    --user node \
    -v ${PWD}:/slidev \
    -p 3030:3030 \
    tangramor/slidev:latest 'slidev export --with-clicks'
```

If is not currently possible, can you please implement this feature?

**Comment by guillermo-maquieira** [comment]
Hello @fam4r ,

Were you able to solve this issue?

I also get this message:


```
  ●■▲
  Slidev  v0.46.1 

  theme       @slidev/theme-apple-basic
  css engine  unocss
  entry       /slidev/slides.md
browserType.launch: Executable doesn't exist at /home/node/.cache/ms-playwright/chromium-1097/chrome-linux/chrome
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║     npx playwright install                                              ║
║                                                                         ║
║ <3 Playwright Team                                                      ║
╚═════════════════════════════════════════════════════════════════════════╝
    at exportSlides (/slidev/node_modules/@slidev/cli/dist/export-T7HYPK5J.mjs:127:34)
    at async Object.handler (/slidev/node_modules/@slidev/cli/dist/cli.mjs:365:22) {
  name: 'Error'
}
```

When running `docker exec -i slidev npx slidev export` through command line.

@tangramor can you reproduce this from your side?

Thanks!

**Comment by tangramor** [comment]
OK, I created another image to support export feature, please refer to the updated README or read the manual in https://hub.docker.com/r/tangramor/slidev
